name: deploy production

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    # if: github.event.pull_request.merged == true
    name: Deployment avalite-ssr production
    runs-on: ubuntu-latest
    steps:
      - name: checkout to branch
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install
      - run: npm run build

      - name: Get serveless.yml from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: production/avalite-ssr
          OUTPUT_PATH: 'serverless.yml'

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://avalite-ssr-production/.serverless .serverless --delete

      - name: serverless deploy
        uses: serverless/github-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://avalite-ssr-production/.serverless --delete